### PR TITLE
Atom In ROS2 documentation page

### PR DESCRIPTION
**Pull request by dimaxano**
Hi!

Here is the documentation page on how to use Atom in ROS2.
I think it would be nice if someone but me follows that steps, prepares environment and see if it works.

### CODE REVIEW

**Comment by miguelriemoliveira** [comment]
> Hi!
> 
> Here is the documentation page on how to use Atom in ROS2. I think it would be nice if someone but me follows that steps, prepares environment and see if it works.

Thanks @dimaxano . I will give it a shot later this week and let you know how it went.

**Comment by miguelriemoliveira** [comment]
Hi @dimaxano ,

sorry for the delay. I am finalizing the classes for the semester and it gets more busy at this time of year.

So I was trying your instructions. Some comments:

1. When running 

```
cd ~/noetic_shared/calib_ws/src && git clone git@github.com:cmrobotics/atom.git && git clone https://github.com/cmrobotics/rosbags.git
```

we get a no such file or directory

It should be **noetic_shared_dir**

     cd ~/noetic_shared_dir/calib_ws/src && git clone git@github.com:cmrobotics/atom.git && git clone https://github.com/cmrobotics/rosbags.git


2. When you run 

```
cd ~/noetic_shared_dir/calib_ws/src && git clone git@github.com:cmrobotics/atom.git && git clone https://github.com/cmrobotics/rosbags.git
```

Why do you need to get the cmrobotics fork of atom? Why not the main atom repo, i.e.:

```
cd ~/noetic_shared_dir/calib_ws/src && git clone git@github.com:lardemua/atom.git && git clone https://github.com/cmrobotics/rosbags.git
```


4. If you use a method of giving a concrete example as in 

```
mkdir -p ~/noetic_shared_dir/calib_ws/src && mkdir -p ~/noetic_shared_dir/datasets && mkdir -p ~/noetic_shared_dir/bagfiles
```

instead of an abstract one as in 

```
mkdir -p \<your_noetic_dir\>/calib_ws/src && mkdir -p ~/noetic_shared_dir/datasets && mkdir -p ~/noetic_shared_dir/bagfiles
```

I would stick to the concrete example method and so this instruction 

```
docker build --tag=ros:noetic <path_to_atom_repo>/dockerfiles/noetic
```

would become:

```
    docker build --tag=ros:noetic ~/noetic_shared_dir/calib_ws/src/atom/dockerfiles/noetic
```


5. inside the container

There are 3 instructions, to be executed in two different paths, so perhaps first we could change the order and say:

Go to the rosbags folder

    cd ~/calib_ws/src/rosbags/

and then install using

   python3 -m pip install .

Then, for the package compilation, it would become:

Go to the the calib_ws

    cd ~/calib_ws/

and then compile

    catkin_make

and finally source 

   source devel/setup.bash

With the changes above I was able to run the instructions. 

@dimaxano can you make the changes you think make sense after these suggestions?

**Comment by dimaxano** [comment]
Thanks for the suggestions, @miguelriemoliveira. They all make sense, just fixed them.

I've also added a Calibration section where I tell how to pass the robot description file.

**Comment by miguelriemoliveira** [comment]
> Thanks for the suggestions, @miguelriemoliveira. They all make sense, just fixed them.
> 
> I've also added a Calibration section where I tell how to pass the robot description file.

Thanks @dimaxano .

I will merge right now.

**Comment by miguelriemoliveira** [comment]
Just deployed the documentation. Should be online in a few minutes ...

**Comment by miguelriemoliveira** [comment]
Its online:

https://lardemua.github.io/atom_documentation/atom_in_ros2/

Thanks again for the support @dimaxano .

**Pull request merged**
